export const TEXT_EN: { [key: string]: string } = {
  primerTitulo: 'My Quinceañera',
  tNombres: 'Francis <br>Valeria',
  traduccion: 'Ver invitación en español',
  pCancion: 'Your browser does not support the audio element.',
  subTitulo: 'You are invited!',
  mensajeBienvenida1: 'There are moments in life that are important on their own, but sharing them with those we love the most turns them into unique and unforgettable memories.',
  mensajeBienvenida2: 'With God’s blessing and the great love I receive from my family, I am very joyful to be reaching a unique moment in my life...<br><br>And because you are part of my life, I wish for you to share with me the joy of celebrating together', mensajeBienvenida3: 'Cordially invites you to enjoy <br>this magical day with me.',
  soloFaltan: 'Countdown:',
  counterDias: 'Days',
  counterHoras: 'Hours',
  counterMinutos: 'Minutes',
  counterSeg: 'Seconds',
  //NOMBRE DE PADRES
  tituloInicialPadres: 'With the blessing of God',
  subTituloInicialPadres: 'and our parents',
  nomPadres: 'My Parents',
  textPadres: 'Thanks to God´s blessing and all the love my parents have given me, I have reached the moment when I will leave my childhood behind and begin this new chapter of my life.',
  nomPadrinos: 'My Godparents',
  textPadrinos: 'Godparents are not found, they are chosen with the heart — and my heart chose you both.',
  //FECHA Y BODA
  textFechaBoda: 'Saturday:',
  fechaBoda: '10&nbsp;•&nbsp;01&nbsp;•&nbsp;2027',
  // CALENDAR
  mes0: 'January',
  mes1: 'February',
  mes2: 'March',
  mes3: 'April',
  mes4: 'May',
  mes5: 'June',
  mes6: 'July',
  mes7: 'August',
  mes8: 'September',
  mes9: 'October',
  mes10: 'November',
  mes11: 'December',
  dia0: 's',
  dia1: 'm',
  dia2: 't',
  dia3: 'w',
  dia4: 'th',
  dia5: 'f',
  dia6: 's',
  //GUARDAR LA FECHA
  guardaFecha: 'Save the date',
  // CEREMONIA Y RECEPCIÓN
  tituloCeremonia: 'Ceremony',
  direccionCeremonia: '<b>Mission San Fernando Rey de España</b><br>15151 San Fernando Mission Blvd, Mission Hills, CA 91345, United States',
  horaCeremonia: 'Time: 6:30 P.M. - 1:00 A.M.',
  ubicacion: 'SEE LOCATION',
  tituloRecepcion: 'Celebration',
  textoInv: 'Valet Parking complementary',
  direccionRecepcion: '<b>The Landmark</b><br>10635 Woodman Ave, Mission Hills, CA 91345, United States',
  horaRecepcion: 'Time: 6:00 P.M.',
  //ITINERARIO
  titleTimeline: 'Timeline',
  timelinejpg: 'assets/IMGTIME(EN).png',
  // VESTIMENTA O DRESS CODE
  tituloVestimenta: 'Dress Code',
  textoVestimentaUno: 'Formal Style',
  textoVestimentaDos: 'The most important thing is that you feel comfortable and special on this meaningful day, so choose an outfit that makes you feel your best. We kindly ask that you avoid wearing pink tones.',  // NUESTROS MOMENTOS
  tituloMomentos: 'Photo gallery',
  textoMomentos: 'Help grow the memories of this special day. Scan the QR code to share your moments and be part of this beautiful celebration.',
  buttonMomentos: 'UPLOAD PHOTOS!',
  // REGALOS
  tituloRegalo: 'Gifts',
  subtituloRegalo: '<b>Cash<b>',
  textoRegaloUno: 'Cash gifts are always welcome but never <br>obligatory. All we ask is that you be here with us.',
  textoRegaloDos: 'Your presence is the most important thing to me and the best gift I can receive; however, if you would like to give a little something, I’m sharing this option with you:',
  textoRegOp1: 'Money Envelope Shower',
  textoRegOp2: 'Gift Registry',
  // NO NIÑOS
  tituloKids: 'Important Note',
  textoKids: 'We love children and their joy always lights up our lives. However, for this special celebration, the event will be adults only. We appreciate your understanding.',
  tituloHotel: 'Suggestions',
  clic1: 'Click to view options:',
  website: 'Website',
  tituloVuelos: 'Accommodations',
  telefonoLabel: 'Phone',
  aviancaTexto1: 'We are sharing the contact link of our makeup artist and hairstylist. You can contact her directly.',
  aviancaTexto2: 'We suggest these nearby hotels for your convenience!',
  aviancaTexto3: 'Makeup Artists',
  confirmacionWhatsapp: 'https://wa.me/13052995211?text=Hello,%20thank%20you%20for%20the%20invitation%20to%20your%20party.%20I%E2%80%99m%20happy%20to%20join%20you%20on%20this%20special%20day.%20I%20confirm%20my%20attendance.',

  boaTexto1: 'BoA is a Bolivian airline that also departs from Miami. It is a nighttime flight, but you can also choose daytime flights.',
  boaTexto2: 'They are affordable and the layover happens later in Santa Cruz, Bolivia. You can fly nonstop for 6 hours and then take a one-hour flight to La Paz.',
  boaTexto3: 'This is also one of the easiest and cheapest ways to get to Bolivia!',
  tituloHotelesLaPaz: 'Hotels in La Paz',

  // PASES
  tituloPases: 'Passes',
  textoPasesUno: 'Are reserved for you',
  textoPasesDos: '2 seats in your honor.',
  //CONFIRMACIÓN DE ASISTENCIA
  tituloConfirmacion: 'Confirm Your <br>Attendance',
  textoConfirmacionUno: 'Please confirm your assistance as soon as possible.',
  textoConfirmacionDos: 'assistance as soon as possible.',
  textoConfirmacionTres: 'As we celebrate Isabella and this important moment in her life, we kindly ask that attendance be limited to guests aged 8 and older. We appreciate your understanding.',
  buttonConfirmacion: 'WhatsApp',
  buttonForms: 'CONFIRM',
  // CONFIRMACION
  mensaje_confirmado: 'RSVP',
  yaConfirAsistencia: 'You have already confirmed your attendance!',
  mensajeBienvenidaConfirm:
    'We look forward to seeing you. Please confirm your attendance before ',
  cantidadAsistentes: 'The number of seats reserved for you is:',
  alertCantidadAsis: 'Number of attendees',
  alertaPuedesConfirmarHasta: 'You can confirm until',
  alertaMinimoConfirmaciones: 'You must enter at least one guest.',
  invitNoEspecificado:
    'We noticed that the names of your companions were not specified. We would greatly appreciate it if you could provide this information to help us with better organization.',
  mesa: 'Your seat is at table number:',
  NombreInvitadoInput: 'Write your name here',
  botonConfirmacion: 'Confirm',
  totalInvitadosConfirmado: 'Reserved seats:',
  despedidaEsperamosVerte: 'We look forward to seeing you!',
  acompañantesAgregados: 'Added companions:',
  txtNoAsistencia:
    'We’re sorry you won’t be able to join us, but we hope to see you very soon!',
  debesIngresarInvitados: 'You must enter at least one guest.',
  puedesConfirmar: 'You can confirm until',
  invitadoConfirmacion: 'Guest',
  asistentesAgregados: 'Added guests:',
  teEsperamos: 'We look forward to seeing you!',
  asistiras: 'Will you be attending?',
  siAsistire: 'Yes, I will attend',
  noAsistira: 'I will not attend',
  estasSeguro: 'Are you sure?',
  fechaConfirmacionCaducada:
    'The deadline to confirm your attendance has passed!',
  fechaConfirmacionCaducadaDos: 'If you’d like, you can get in touch with us!',
  // POP-UP CONFIRMATION WINDOW
  confirmAsistenciatitle: 'Do you confirm this attendance?',
  opcancelar: 'Cancel',
  sininvitadostitle: 'Confirmation',
  sininvitadostxt: 'To continue, please make sure to enter at least one person who will attend.',
  txtnoagregare: 'I will not add',
  txtsiagregare: 'I will add',
  txtdetalleconf: 'Please make sure to write your name and, if applicable, the names of your companions.',
  // DESPEDIDA
  tituloDespedida: 'We look forward to seeing you!',
  DespedidaNombres: 'Valeria and Josué',
  // GLASMMY
  textoGlasmmy: 'Created with love by',
  glasmmy: 'GlasmmyDigital'

}
